<?php
    
if( ! defined( 'ABSPATH' ) ) {
    die;
}

if( ! class_exists( 'Overlap_Shortcode' ) ) {

    class Overlap_Shortcode{

    	function __construct() {

    		if( !class_exists('Wyde_Core') ){
    			// Remove all filters to remove the Visual Composer errors.
    			remove_all_filters( 'the_content' );

    			// Display the error message "Wyde Core plugin is required"
    			//add_filter( 'the_content', array($this, 'shortcode_error') );

    			// Remove shortcodes from content, display the plain content instead
    			add_filter( 'the_content', array($this, 'remove_shortcodes_from_content') );
    			return;
    		}

    		/* Visual Composer hooks */
    		add_action( 'vc_before_init', array($this, 'init_shortcodes') );
            add_filter( 'vc_load_default_templates', array($this, 'load_templates'), 100 );        
            add_filter( 'vc_iconpicker-type-fontawesome', array($this, 'get_font_awesome_icons'), 100 );
            add_filter( 'vc_iconpicker-type-linecons', array($this, 'get_linecons_icons'), 100 );
            add_filter( 'vc_iconpicker-type-bigmug_line', array($this, 'get_bigmug_line_icons'), 100 );
            add_filter( 'vc_iconpicker-type-simple_line', array($this, 'get_simple_line_icons'), 100 );

            /* Wyde Core hooks */
            add_action( 'wyde_load_shortcodes', array($this, 'load_shortcodes') );
    		add_action( 'wyde_update_plugins_shortcodes', array($this, 'update_plugins_shortcodes') );
    		add_filter( 'wyde_blog_masonry_layout', array($this, 'get_blog_masonry_layout') );
            add_filter( 'wyde_portfolio_masonry_layout', array($this, 'get_portfolio_masonry_layout') );
            add_filter( 'wyde_gallery_masonry_layout', array($this, 'get_gallery_masonry_layout') );
            add_filter( 'wyde_google_maps_api_key', array($this, 'get_google_maps_api_key') );
            add_filter( 'wyde_iconpicker_options', array($this, 'get_iconpicker_options'), 100 );            
            
    	}

    	function Overlap_Shortcode(){
    		$this->__construct();
    	}    	

    	function remove_shortcodes_from_content( $content ){

    		$pattern = get_shortcode_regex();
		    $content = preg_replace_callback("/$pattern/s", 'overlap_remove_shortcode', $content);
		    $content = str_replace(']]>', ']]&gt;', $content);

    		$content = 	'<div class="w-section"><div class="container"><div class="row"><div class="col col-12">'
			    		.$content
			    		.'</div></div></div></div>';

    		return $content;
    	}

    	function shortcode_error( $content ){
    		$content = '<div class="w-section"><div class="container"><div class="row"><div class="col col-12">'
    		.'<div class="page-error-wrapper">'
    		.'<h4 class="page-error-title">'. esc_html__('Wyde Core plugin is required!', 'overlap') .'</h4>'
    		.'<h6 class="page-error-text">'. esc_html__('This theme requires Wyde Core plugin for rendering shortcodes and content.', 'overlap') .'</h6>'
    		.'</div>'
    		.'</div></div></div></div>';
    		return $content;
    	}

    	public function load_templates($templates){
    		return $templates;
    	}

    	public function init_shortcodes(){
			//Set Shortcodes Templates Directory
            vc_set_shortcodes_templates_dir( get_template_directory() .'/templates/shortcodes' );
    	}

        /* Find and include all shortcodes within shortcodes folder */
	    public function load_shortcodes() {

            $files = glob( get_template_directory(). '/inc/shortcodes/*.php' );
            
            if( is_array($files) ){
    		    foreach( $files as $filename ) {
    			    include_once( $filename );
    		    }
            }
            
		    $this->update_shortcodes();
	    }

		function update_shortcodes(){
 
			/***************************************** 
            /* SINGLE IMAGE
            /*****************************************/
            vc_map( array(
                'name' => esc_html__( 'Single Image', 'overlap' ),
                'base' => 'vc_single_image',
                'icon' => 'wyde-icon image-icon',
                'weight'    => 998,
                'category' => esc_html__( 'Content', 'overlap' ),
                'description' => esc_html__( 'Insert an image', 'overlap' ),
                'params' => array(
                    array(
                        'param_name' => 'image',
                        'type' => 'attach_image',
                        'heading' => esc_html__( 'Image', 'overlap' ),                      
                        'description' => esc_html__( 'Select an image from media library.', 'overlap' )
                    ),
                    array(
                        'param_name' => 'img_size',
                        'type' => 'dropdown',
                        'heading' => esc_html__( 'Image Size', 'overlap' ),                     
                        'value' => array(
                            esc_html__('Thumbnail (150x150)', 'overlap' ) => 'thumbnail',
                            esc_html__('Medium (340x340)', 'overlap' ) => 'overlap-medium',
                            esc_html__('Large (640x640)', 'overlap' ) => 'overlap-large',
                            esc_html__('Extra Large (960x960)', 'overlap' ) => 'overlap-xlarge',
                            esc_html__('Full Width (min-width: 1280px)', 'overlap' ) => 'overlap-fullwidth',
                            esc_html__('Original', 'overlap' ) => 'full',
                        ),
                        'std'   => 'full',
                        'description' => esc_html__( 'Select image size.', 'overlap' )
                    ),
                    array(
                        'param_name' => 'style',
                        'type' => 'dropdown',
                        'heading' => esc_html__( 'Image Style', 'overlap' ),                        
                        'admin_label' => true,
                        'value' => array(
                            esc_html__('Default', 'overlap' ) => '',
                            esc_html__('Border', 'overlap' ) => 'border',
                            esc_html__('Outline', 'overlap' ) => 'outline',
                            esc_html__('Shadow', 'overlap' ) => 'shadow',
                            esc_html__('Round', 'overlap' ) => 'round',
                            esc_html__('Round Border', 'overlap' ) => 'round-border',
                            esc_html__('Round Outline', 'overlap' ) => 'round-outline', 
                            esc_html__('Round Shadow', 'overlap' ) => 'round-shadow', 
                            esc_html__('Circle', 'overlap' ) => 'circle', 
                            esc_html__('Circle Border', 'overlap' ) => 'circle-border', 
                            esc_html__('Circle Outline', 'overlap' ) => 'circle-outline',
                            esc_html__('Circle Shadow', 'overlap' ) => 'circle-shadow',
                        ),
                        'description' => esc_html__( 'Select image alignment.', 'overlap' )
                    ),
                    array(
                        'param_name' => 'border_color',
                        'type' => 'colorpicker',
                        'heading' => esc_html__( 'Border Color', 'overlap' ),                       
                        'description' => esc_html__( 'Select image border color.', 'overlap' ),
                        'dependency' => array(
                            'element' => 'style',
                            'value' => array( 'border', 'outline', 'round-border', 'round-outline', 'circle-border', 'circle-outline' )
                        )
                    ),
                    array(
                        'param_name' => 'alignment',
                        'type' => 'dropdown',
                        'heading' => esc_html__( 'Image Alignment', 'overlap' ),                        
                        'value' => array(
                            esc_html__( 'Align Left', 'overlap' ) => 'left',
                            esc_html__( 'Align Center', 'overlap' ) => 'center',
                            esc_html__( 'Align Right', 'overlap' ) => 'right',
                        ),
                        'description' => esc_html__( 'Select image alignment.', 'overlap' )
                    ),
                    array(
                        'param_name' => 'onclick',
                        'type' => 'dropdown',
                        'heading' => esc_html__( 'On Click Action', 'overlap' ),                        
                        'value' => array(
                            esc_html__( 'None', 'overlap' ) => '',
                            esc_html__( 'Link to large image', 'overlap' ) => 'img_link_large',
                            esc_html__( 'Open prettyPhoto', 'overlap' ) => 'link_image',
                            esc_html__( 'Open custom link', 'overlap' ) => 'custom_link',
                        ),
                        'description' => esc_html__( 'Select action for click action.', 'overlap' ),
                        'std' => '',
                    ),
                    array(
                        'param_name' => 'link',
                        'type' => 'href',
                        'heading' => esc_html__( 'Image Link', 'overlap' ),                     
                        'description' => esc_html__( 'Set an image link.', 'overlap' ),
                        'dependency' => array(
                            'element' => 'onclick',
                            'value' => 'custom_link',
                        ),
                    ),
                    array(
                        'param_name' => 'link_target',
                        'type' => 'dropdown',
                        'heading' => esc_html__( 'Link Target', 'overlap' ),                        
                        'value' => array(
                            esc_html__( 'Same window', 'overlap' ) => '_self',
                            esc_html__( 'New window', 'overlap' ) => "_blank",
                        ),
                        'dependency' => array(
                            'element' => 'onclick',
                            'value' =>  array( 'custom_link', 'img_link_large' )
                        )
                    ),
                    array(
                        'param_name' => 'animation',
                        'type' => 'wyde_animation',
                        'heading' => esc_html__('Animation', 'overlap'),                        
                        'description' => esc_html__('Select a CSS3 Animation that applies to this element.', 'overlap')
                    ),
                    array(
                        'param_name' => 'animation_delay',
                        'type' => 'textfield',
                        'heading' => esc_html__('Animation Delay', 'overlap'),                                              
                        'description' => esc_html__('Defines when the animation will start (in seconds). Example: 0.5, 1, 2, ...', 'overlap'),
                        'dependency' => array(
                            'element' => 'animation',
                            'not_empty' => true
                        )
                    ),
                    array(
                        'param_name' => 'el_class',
                        'type' => 'textfield',
                        'heading' => esc_html__( 'Extra CSS Class', 'overlap' ),                        
                        'description' => esc_html__( 'Style particular content element differently - add a class name and refer to it in custom CSS.', 'overlap' )
                    ),
                    array(
                        'param_name' => 'css',
                        'type' => 'css_editor',
                        'heading' => esc_html__( 'Css', 'overlap' ),                        
                        'group' => esc_html__( 'Design Options', 'overlap' )
                    ) 
                )
            ) );
            
		}

		public function update_plugins_shortcodes(){
            // Update plugins
        }

        public function get_google_maps_api_key(){
        	return overlap_get_option('google_maps_api_key');
        }

        public function get_iconpicker_options($options){
        	$options = array(
	            array(
	            	'param_name' => 'icon_set',
	                'type' => 'dropdown',
	                'heading' => esc_html__( 'Icon Set', 'overlap' ),
	                'value' => array(
		                'Font Awesome' => '',
		                'Typicons' => 'typicons',
		                'Linecons' => 'linecons',
	                    'Big Mug Line' => 'bigmug_line',
	                    'Simple Line' => 'simple_line',
	                ),	                
	                'description' => esc_html__('Select an icon set.', 'overlap')
	            ),
	            array(
	            	'param_name' => 'icon',
	                'type' => 'iconpicker',
	                'heading' => esc_html__( 'Icon', 'overlap' ),	                
	                'settings' => array(
		                'emptyIcon' => true, 
		                'iconsPerPage' => 4000, 
	                ),
	                'description' => esc_html__('Select an icon.', 'overlap'),
	                'dependency' => array(
		                'element' => 'icon_set',
		                'is_empty' => true,
	                ),
	            ),
	            array(
	            	'param_name' => 'icon_typicons',
	                'type' => 'iconpicker',
	                'heading' => esc_html__( 'Icon', 'overlap' ),	                
	                'settings' => array(
	                    'emptyIcon' => true, 
	                    'type' => 'typicons',
	                    'iconsPerPage' => 4000, 
	                ),
	                'description' => esc_html__('Select an icon.', 'overlap'),
	                'dependency' => array(
	                    'element' => 'icon_set',
	                    'value' => 'typicons',
	                ),
	            ),
	            array(
	            	'param_name' => 'icon_linecons',
	                'type' => 'iconpicker',
	                'heading' => esc_html__( 'Icon', 'overlap' ),	                
	                'settings' => array(
	                    'emptyIcon' => true, 
	                    'type' => 'linecons',
	                    'iconsPerPage' => 4000,
	                ),
	                'description' => esc_html__('Select an icon.', 'overlap'),
	                'dependency' => array(
	                    'element' => 'icon_set',
	                    'value' => 'linecons',
	                ),
	            ),
	            array(
					'param_name' => 'icon_bigmug_line',
	                'type' => 'iconpicker',
	                'heading' => esc_html__( 'Icon', 'overlap' ),	                
	                'settings' => array(
	                    'emptyIcon' => true, 
	                    'type' => 'bigmug_line',
	                    'iconsPerPage' => 4000,
	                ),
	                'description' => esc_html__('Select an icon.', 'overlap'),
	                'dependency' => array(
	                    'element' => 'icon_set',
	                    'value' => 'bigmug_line',
	                ),
	            ),
	            array(
	            	'param_name' => 'icon_simple_line',
	                'type' => 'iconpicker',
	                'heading' => esc_html__( 'Icon', 'overlap' ),                
	                'settings' => array(
	                    'emptyIcon' => true, 
	                    'type' => 'simple_line',
	                    'iconsPerPage' => 4000,
	                ),
	                'description' => esc_html__('Select an icon.', 'overlap'),
	                'dependency' => array(
	                    'element' => 'icon_set',
	                    'value' => 'simple_line',
	                ),
	            ),
                        

            );

			return $options;
        }		

		public function get_font_awesome_icons( $icons ){

            $icons = array(
                "Web Application Icons" => array(
                    array( "fa fa-adjust" =>  "Adjust" ),
                    array( "fa fa-anchor" =>  "Anchor" ),
                    array( "fa fa-archive" =>  "Archive" ),
                    array( "fa fa-area-chart" =>  "Area Chart" ),
                    array( "fa fa-arrows" =>  "Arrows" ),
                    array( "fa fa-arrows-h" =>  "Arrows Horizontal" ),
                    array( "fa fa-arrows-v" =>  "Arrows Vertical" ),
                    array( "fa fa-asterisk" =>  "Asterisk" ),
                    array( "fa fa-at" =>  "At" ),
                    array( "fa fa-ban" =>  "Ban" ),
                    array( "fa fa-bar-chart" =>  "Bar Chart" ),
                    array( "fa fa-barcode" =>  "Barcode" ),
                    array( "fa fa-bars" =>  "Bars" ),
                    array( "fa fa-beer" =>  "Beer" ),
                    array( "fa fa-bell" =>  "Bell" ),
                    array( "fa fa-bell-o" =>  "Bell Outlined" ),
                    array( "fa fa-bell-slash" =>  "Bell Slash" ),
                    array( "fa fa-bell-slash-o" =>  "Bell Slash Outlined" ),
                    array( "fa fa-bicycle" =>  "Bicycle" ),
                    array( "fa fa-binoculars" =>  "Binoculars" ),
                    array( "fa fa-birthday-cake" =>  "Birthday Cake" ),
                    array( "fa fa-bolt" =>  "Lightning Bolt" ),
                    array( "fa fa-bomb" =>  "Bomb" ),
                    array( "fa fa-book" =>  "Book" ),
                    array( "fa fa-bookmark" =>  "Bookmark" ),
                    array( "fa fa-bookmark-o" =>  "Bookmark Outlined" ),
                    array( "fa fa-briefcase" =>  "Briefcase" ),
                    array( "fa fa-bug" =>  "Bug" ),
                    array( "fa fa-building" =>  "Building" ),
                    array( "fa fa-building-o" =>  "Building Outlined" ),
                    array( "fa fa-bullhorn" =>  "bullhorn" ),
                    array( "fa fa-bullseye" =>  "Bullseye" ),
                    array( "fa fa-bus" =>  "Bus" ),
                    array( "fa fa-calculator" =>  "Calculator" ),
                    array( "fa fa-calendar" =>  "Calendar" ),
                    array( "fa fa-calendar-o" =>  "Calendar-o" ),
                    array( "fa fa-camera" =>  "Camera" ),
                    array( "fa fa-camera-retro" =>  "Camera-retro" ),
                    array( "fa fa-car" =>  "Car" ),
                    array( "fa fa-caret-square-o-down" =>  "Caret Square Outlined Down" ),
                    array( "fa fa-caret-square-o-left" =>  "Caret Square Outlined Left" ),
                    array( "fa fa-caret-square-o-right" =>  "Caret Square Outlined Right" ),
                    array( "fa fa-caret-square-o-up" =>  "Caret Square Outlined Up" ),
                    array( "fa fa-cc" =>  "Closed Captions" ),
                    array( "fa fa-certificate" =>  "Certificate" ),
                    array( "fa fa-check" =>  "Check" ),
                    array( "fa fa-check-circle" =>  "Check Circle" ),
                    array( "fa fa-check-circle-o" =>  "Check Circle Outlined" ),
                    array( "fa fa-check-square" =>  "Check Square" ),
                    array( "fa fa-check-square-o" =>  "Check Square Outlined" ),
                    array( "fa fa-child" =>  "Child" ),
                    array( "fa fa-circle" =>  "Circle" ),
                    array( "fa fa-circle-o" =>  "Circle Outlined" ),
                    array( "fa fa-circle-o-notch" =>  "Circle Outlined Notched" ),
                    array( "fa fa-circle-thin" =>  "Circle Outlined Thin" ),
                    array( "fa fa-clock-o" =>  "Clock Outlined" ),
                    array( "fa fa-cloud" =>  "Cloud" ),
                    array( "fa fa-cloud-download" =>  "Cloud Download" ),
                    array( "fa fa-cloud-upload" =>  "Cloud Upload" ),
                    array( "fa fa-code" =>  "Code" ),
                    array( "fa fa-code-fork" =>  "Code-fork" ),
                    array( "fa fa-coffee" =>  "Coffee" ),
                    array( "fa fa-cog" =>  "Cog" ),
                    array( "fa fa-cogs" =>  "Cogs" ),
                    array( "fa fa-comment" =>  "Comment" ),
                    array( "fa fa-comment-o" =>  "Comment-o" ),
                    array( "fa fa-comments" =>  "Comments" ),
                    array( "fa fa-comments-o" =>  "Comments-o" ),
                    array( "fa fa-compass" =>  "Compass" ),
                    array( "fa fa-copyright" =>  "Copyright" ),
                    array( "fa fa-credit-card" =>  "credit-card" ),
                    array( "fa fa-crop" =>  "Crop" ),
                    array( "fa fa-crosshairs" =>  "Crosshairs" ),
                    array( "fa fa-cube" =>  "Cube" ),
                    array( "fa fa-cubes" =>  "Cubes" ),
                    array( "fa fa-cutlery" =>  "Cutlery" ),
                    array( "fa fa-database" =>  "Database" ),
                    array( "fa fa-desktop" =>  "Desktop" ),
                    array( "fa fa-dot-circle-o" =>  "Dot Circle O" ),
                    array( "fa fa-download" =>  "Download" ),
                    array( "fa fa-ellipsis-h" =>  "Ellipsis Horizontal" ),
                    array( "fa fa-ellipsis-v" =>  "Ellipsis Vertical" ),
                    array( "fa fa-envelope" =>  "Envelope" ),
                    array( "fa fa-envelope-o" =>  "Envelope Outlined" ),
                    array( "fa fa-envelope-square" =>  "Envelope Square" ),
                    array( "fa fa-eraser" =>  "Eraser" ),
                    array( "fa fa-exchange" =>  "Exchange" ),
                    array( "fa fa-exclamation" =>  "Exclamation" ),
                    array( "fa fa-exclamation-circle" =>  "Exclamation Circle" ),
                    array( "fa fa-exclamation-triangle" =>  "Exclamation Triangle" ),
                    array( "fa fa-external-link" =>  "External Link" ),
                    array( "fa fa-external-link-square" =>  "External Link Square" ),
                    array( "fa fa-eye" =>  "Eye" ),
                    array( "fa fa-eye-slash" =>  "Eye Slash" ),
                    array( "fa fa-eyedropper" =>  "Eyedropper" ),
                    array( "fa fa-fax" =>  "Fax" ),
                    array( "fa fa-female" =>  "Female" ),
                    array( "fa fa-fighter-jet" =>  "Fighter-jet" ),
                    array( "fa fa-file-archive-o" =>  "Archive File Outlined" ),
                    array( "fa fa-file-audio-o" =>  "Audio File Outlined" ),
                    array( "fa fa-file-code-o" =>  "Code File Outlined" ),
                    array( "fa fa-file-excel-o" =>  "Excel File Outlined" ),
                    array( "fa fa-file-image-o" =>  "Image File Outlined" ),
                    array( "fa fa-file-pdf-o" =>  "PDF File Outlined" ),
                    array( "fa fa-file-powerpoint-o" =>  "Powerpoint File Outlined" ),
                    array( "fa fa-file-video-o" =>  "Video File Outlined" ),
                    array( "fa fa-file-word-o" =>  "Word File Outlined" ),
                    array( "fa fa-film" =>  "Film" ),
                    array( "fa fa-filter" =>  "Filter" ),
                    array( "fa fa-fire" =>  "Fire" ),
                    array( "fa fa-fire-extinguisher" =>  "Fire-extinguisher" ),
                    array( "fa fa-flag" =>  "Flag" ),
                    array( "fa fa-flag-checkered" =>  "Flag-checkered" ),
                    array( "fa fa-flag-o" =>  "Flag Outlined" ),
                    array( "fa fa-flask" =>  "Flask" ),
                    array( "fa fa-folder" =>  "Folder" ),
                    array( "fa fa-folder-o" =>  "Folder Outlined" ),
                    array( "fa fa-folder-open" =>  "Folder Open" ),
                    array( "fa fa-folder-open-o" =>  "Folder Open Outlined" ),
                    array( "fa fa-frown-o" =>  "Frown Outlined" ),
                    array( "fa fa-futbol-o" =>  "Futbol Outlined" ),
                    array( "fa fa-gamepad" =>  "Gamepad" ),
                    array( "fa fa-gavel" =>  "Gavel" ),
                    array( "fa fa-gift" =>  "Gift" ),
                    array( "fa fa-glass" =>  "Glass" ),
                    array( "fa fa-globe" =>  "Globe" ),
                    array( "fa fa-graduation-cap" =>  "Graduation Cap" ),
                    array( "fa fa-hdd-o" =>  "HDD" ),
                    array( "fa fa-headphones" =>  "Headphones" ),
                    array( "fa fa-heart" =>  "Heart" ),
                    array( "fa fa-heart-o" =>  "Heart Outlined" ),
                    array( "fa fa-history" =>  "History" ),
                    array( "fa fa-home" =>  "Home" ),
                    array( "fa fa-inbox" =>  "Inbox" ),
                    array( "fa fa-info" =>  "Info" ),
                    array( "fa fa-info-circle" =>  "Info Circle" ),
                    array( "fa fa-key" =>  "Key" ),
                    array( "fa fa-keyboard-o" =>  "Keyboard Outlined" ),
                    array( "fa fa-language" =>  "Language" ),
                    array( "fa fa-laptop" =>  "Laptop" ),
                    array( "fa fa-leaf" =>  "Leaf" ),
                    array( "fa fa-lemon-o" =>  "Lemon Outlined" ),
                    array( "fa fa-level-down" =>  "Level Down" ),
                    array( "fa fa-level-up" =>  "Level Up" ),
                    array( "fa fa-life-ring" =>  "Life Ring" ),
                    array( "fa fa-lightbulb-o" =>  "Lightbulb Outlined" ),
                    array( "fa fa-line-chart" =>  "Line Chart" ),
                    array( "fa fa-location-arrow" =>  "Location-arrow" ),
                    array( "fa fa-lock" =>  "Lock" ),
                    array( "fa fa-magic" =>  "Magic" ),
                    array( "fa fa-magnet" =>  "Magnet" ),
                    array( "fa fa-male" =>  "Male" ),
                    array( "fa fa-map-marker" =>  "Map-marker" ),
                    array( "fa fa-meh-o" =>  "Meh Outlined" ),
                    array( "fa fa-microphone" =>  "Microphone" ),
                    array( "fa fa-microphone-slash" =>  "Microphone Slash" ),
                    array( "fa fa-minus" =>  "Minus" ),
                    array( "fa fa-minus-circle" =>  "Minus Circle" ),
                    array( "fa fa-minus-square" =>  "Minus Square" ),
                    array( "fa fa-minus-square-o" =>  "Minus Square Outlined" ),
                    array( "fa fa-mobile" =>  "Mobile Phone" ),
                    array( "fa fa-money" =>  "Money" ),
                    array( "fa fa-moon-o" =>  "Moon Outlined" ),
                    array( "fa fa-music" =>  "Music" ),
                    array( "fa fa-newspaper-o" =>  "Newspaper Outlined" ),
                    array( "fa fa-paint-brush" =>  "Paint Brush" ),
                    array( "fa fa-paper-plane" =>  "Paper Plane" ),
                    array( "fa fa-paper-plane-o" =>  "Paper Plane Outlined" ),
                    array( "fa fa-paw" =>  "Paw" ),
                    array( "fa fa-pencil" =>  "Pencil" ),
                    array( "fa fa-pencil-square" =>  "Pencil Square" ),
                    array( "fa fa-pencil-square-o" =>  "Pencil Square Outlined" ),
                    array( "fa fa-phone" =>  "Phone" ),
                    array( "fa fa-phone-square" =>  "Phone Square" ),
                    array( "fa fa-picture-o" =>  "Picture Outlined" ),
                    array( "fa fa-pie-chart" =>  "Pie Chart" ),
                    array( "fa fa-plane" =>  "Plane" ),
                    array( "fa fa-plug" =>  "Plug" ),
                    array( "fa fa-plus" =>  "Plus" ),
                    array( "fa fa-plus-circle" =>  "Plus Circle" ),
                    array( "fa fa-plus-square" =>  "Plus Square" ),
                    array( "fa fa-plus-square-o" =>  "Plus Square Outlined" ),
                    array( "fa fa-power-off" =>  "Power Off" ),
                    array( "fa fa-print" =>  "Print" ),
                    array( "fa fa-puzzle-piece" =>  "Puzzle Piece" ),
                    array( "fa fa-qrcode" =>  "QRcode" ),
                    array( "fa fa-question" =>  "Question" ),
                    array( "fa fa-question-circle" =>  "Question Circle" ),
                    array( "fa fa-quote-left" =>  "Quote-left" ),
                    array( "fa fa-quote-right" =>  "Quote-right" ),
                    array( "fa fa-random" =>  "Random" ),
                    array( "fa fa-recycle" =>  "Recycle" ),
                    array( "fa fa-refresh" =>  "Refresh" ),
                    array( "fa fa-reply" =>  "Reply" ),
                    array( "fa fa-reply-all" =>  "Reply-all" ),
                    array( "fa fa-retweet" =>  "Retweet" ),
                    array( "fa fa-road" =>  "Road" ),
                    array( "fa fa-rocket" =>  "Rocket" ),
                    array( "fa fa-rss" =>  "RSS" ),
                    array( "fa fa-rss-square" =>  "RSS Square" ),
                    array( "fa fa-search" =>  "Search" ),
                    array( "fa fa-search-minus" =>  "Search Minus" ),
                    array( "fa fa-search-plus" =>  "Search Plus" ),
                    array( "fa fa-share" =>  "Share" ),
                    array( "fa fa-share-alt" =>  "Share Alt" ),
                    array( "fa fa-share-alt-square" =>  "Share Alt Square" ),
                    array( "fa fa-share-square" =>  "Share Square" ),
                    array( "fa fa-share-square-o" =>  "Share Square Outlined" ),
                    array( "fa fa-shield" =>  "shield" ),
                    array( "fa fa-shopping-cart" =>  "shopping-cart" ),
                    array( "fa fa-sign-in" =>  "Sign In" ),
                    array( "fa fa-sign-out" =>  "Sign Out" ),
                    array( "fa fa-signal" =>  "signal" ),
                    array( "fa fa-sitemap" =>  "Sitemap" ),
                    array( "fa fa-sliders" =>  "Sliders" ),
                    array( "fa fa-smile-o" =>  "Smile Outlined" ),
                    array( "fa fa-sort" =>  "Sort" ),
                    array( "fa fa-sort-alpha-asc" =>  "Sort Alpha Ascending" ),
                    array( "fa fa-sort-alpha-desc" =>  "Sort Alpha Descending" ),
                    array( "fa fa-sort-amount-asc" =>  "Sort Amount Ascending" ),
                    array( "fa fa-sort-amount-desc" =>  "Sort Amount Descending" ),
                    array( "fa fa-sort-asc" =>  "Sort Ascending" ),
                    array( "fa fa-sort-desc" =>  "Sort Descending" ),
                    array( "fa fa-sort-numeric-asc" =>  "Sort Numeric Ascending" ),
                    array( "fa fa-sort-numeric-desc" =>  "Sort Numeric Descending" ),
                    array( "fa fa-space-shuttle" =>  "Space Shuttle" ),
                    array( "fa fa-spinner" =>  "Spinner" ),
                    array( "fa fa-spoon" =>  "spoon" ),
                    array( "fa fa-square" =>  "Square" ),
                    array( "fa fa-square-o" =>  "Square Outlined" ),
                    array( "fa fa-star" =>  "Star" ),
                    array( "fa fa-star-half" =>  "star-half" ),
                    array( "fa fa-star-half-o" =>  "Star Half Outlined" ),
                    array( "fa fa-star-o" =>  "Star Outlined" ),
                    array( "fa fa-suitcase" =>  "Suitcase" ),
                    array( "fa fa-sun-o" =>  "Sun Outlined" ),
                    array( "fa fa-tablet" =>  "tablet" ),
                    array( "fa fa-tachometer" =>  "Tachometer" ),
                    array( "fa fa-tag" =>  "tag" ),
                    array( "fa fa-tags" =>  "tags" ),
                    array( "fa fa-tasks" =>  "Tasks" ),
                    array( "fa fa-taxi" =>  "Taxi" ),
                    array( "fa fa-terminal" =>  "Terminal" ),
                    array( "fa fa-thumb-tack" =>  "Thumb Tack" ),
                    array( "fa fa-thumbs-down" =>  "thumbs-down" ),
                    array( "fa fa-thumbs-o-down" =>  "Thumbs Down Outlined" ),
                    array( "fa fa-thumbs-o-up" =>  "Thumbs Up Outlined" ),
                    array( "fa fa-thumbs-up" =>  "thumbs-up" ),
                    array( "fa fa-ticket" =>  "Ticket" ),
                    array( "fa fa-times" =>  "Times" ),
                    array( "fa fa-times-circle" =>  "Times Circle" ),
                    array( "fa fa-times-circle-o" =>  "Times Circle Outlined" ),
                    array( "fa fa-tint" =>  "tint" ),
                    array( "fa fa-toggle-off" =>  "Toggle Off" ),
                    array( "fa fa-toggle-on" =>  "Toggle On" ),
                    array( "fa fa-trash" =>  "Trash" ),
                    array( "fa fa-trash-o" =>  "Trash Outlined" ),
                    array( "fa fa-tree" =>  "Tree" ),
                    array( "fa fa-trophy" =>  "trophy" ),
                    array( "fa fa-truck" =>  "truck" ),
                    array( "fa fa-tty" =>  "TTY" ),
                    array( "fa fa-umbrella" =>  "Umbrella" ),
                    array( "fa fa-university" =>  "University" ),
                    array( "fa fa-unlock" =>  "unlock" ),
                    array( "fa fa-unlock-alt" =>  "Unlock Alt" ),
                    array( "fa fa-upload" =>  "Upload" ),
                    array( "fa fa-user" =>  "User" ),
                    array( "fa fa-users" =>  "Users" ),
                    array( "fa fa-video-camera" =>  "Video Camera" ),
                    array( "fa fa-volume-down" =>  "volume-down" ),
                    array( "fa fa-volume-off" =>  "volume-off" ),
                    array( "fa fa-volume-up" =>  "volume-up" ),
                    array( "fa fa-wheelchair" =>  "Wheelchair" ),
                    array( "fa fa-wifi" =>  "WiFi" ),
                    array( "fa fa-wrench" =>  "Wrench" ),
                    /*4.3*/
                    array( "fa fa-bed" => "Bed" ),
                    array( "fa fa-cart-arrow-down" => "Cart Arrow Down" ),
                    array( "fa fa-cart-plus" => "Cart Plus" ),
                    array( "fa fa-diamond" => "Diamond" ),
                    array( "fa fa-heartbeat" => "Heartbeat" ),
                    array( "fa fa-motorcycle" => "Motorcycle" ),
                    array( "fa fa-server" => "Server" ),
                    array( "fa fa-ship" => "Ship" ),
                    array( "fa fa-street-view" => "Street View" ),
                    array( "fa fa-user-plus" => "User Plus" ),
                    array( "fa fa-user-secret" => "User Secret" ),
                    array( "fa fa-user-times" => "User Times" ),
                    /*4.4*/
                    array( "fa fa-balance-scale" => "Balance Scale" ),
                    array( "fa fa-battery-empty" => "Battery Empty" ),
                    array( "fa fa-battery-quarter" => "Battery Quarter" ),
                    array( "fa fa-battery-half" => "Battery Half" ),
                    array( "fa fa-battery-three-quarters" => "Battery Three Quarters" ),
                    array( "fa fa-battery-full" => "Battery Full" ),
                    /*4.5*/
                    array( "fa fa-bluetooth" => "Bluetooth" ),
                    array( "fa fa-bluetooth-b" => "Bluetooth B" ),
                    array( "fa fa-hashtag" => "Hashtag" ),
					array( "fa fa-percent" => "Percent" ),
                    array( "fa fa-shopping-bag" => "Shopping Bag" ),
					array( "fa fa-shopping-basket" => "Shopping Basket" ),

                    
                ),
                "File Type Icons" => array(
                    array( "fa fa-file" =>  "File" ),
                    array( "fa fa-file-archive-o" =>  "Archive File Outlined" ),
                    array( "fa fa-file-audio-o" =>  "Audio File Outlined" ),
                    array( "fa fa-file-code-o" =>  "Code File Outlined" ),
                    array( "fa fa-file-excel-o" =>  "Excel File Outlined" ),
                    array( "fa fa-file-image-o" =>  "Image File Outlined" ),
                    array( "fa fa-file-o" =>  "File Outlined" ),
                    array( "fa fa-file-pdf-o" =>  "PDF File Outlined" ),
                    array( "fa fa-file-powerpoint-o" =>  "Powerpoint File Outlined" ),
                    array( "fa fa-file-text" =>  "File Text" ),
                    array( "fa fa-file-text-o" =>  "File Text Outlined" ),
                    array( "fa fa-file-video-o" =>  "Video File Outlined" ),
                    array( "fa fa-file-word-o" =>  "Word File Outlined" ),
                ),
                "Spinner Icons" => array(
                    array( "fa fa-circle-o-notch" =>  "Circle Outlined Notched" ),
                    array( "fa fa-cog" =>  "cog" ),
                    array( "fa fa-refresh" =>  "refresh" ),
                    array( "fa fa-spinner" =>  "Spinner" ),
                ),
                "Form Control Icons" => array(
                    array( "fa fa-check-square" =>  "Check Square" ),
                    array( "fa fa-check-square-o" =>  "Check Square Outlined" ),
                    array( "fa fa-circle" =>  "Circle" ),
                    array( "fa fa-circle-o" =>  "Circle Outlined" ),
                    array( "fa fa-dot-circle-o" =>  "Dot Circle O" ),
                    array( "fa fa-minus-square" =>  "Minus Square" ),
                    array( "fa fa-minus-square-o" =>  "Minus Square Outlined" ),
                    array( "fa fa-plus-square" =>  "Plus Square" ),
                    array( "fa fa-plus-square-o" =>  "Plus Square Outlined" ),
                    array( "fa fa-square" =>  "Square" ),
                    array( "fa fa-square-o" =>  "Square Outlined" ),
                ),
                "Payment Icons" => array(
                    array( "fa fa-cc-amex" =>  "American Express Credit Card" ),
                    array( "fa fa-cc-discover" =>  "Discover Credit Card" ),
                    array( "fa fa-cc-mastercard" =>  "MasterCard Credit Card" ),
                    array( "fa fa-cc-paypal" =>  "Paypal Credit Card" ),
                    array( "fa fa-cc-stripe" =>  "Stripe Credit Card" ),
                    array( "fa fa-cc-visa" =>  "Visa Credit Card" ),
                    array( "fa fa-credit-card" =>  "credit-card" ),
                    array( "fa fa-google-wallet" =>  "Goole Wallet" ),
                    array( "fa fa-paypal" =>  "Paypal" ),
                ),
                "Chart Icons" => array(
                    array( "fa fa-area-chart" =>  "Area Chart" ),
                    array( "fa fa-bar-chart" =>  "Bar Chart" ),
                    array( "fa fa-line-chart" =>  "Line Chart" ),
                    array( "fa fa-pie-chart" =>  "Pie Chart" ),
                ),
                "Currency Icons" => array(
                    array( "fa fa-btc" =>  "Bitcoin (BTC)" ),
                    array( "fa fa-eur" =>  "Euro (EUR)" ),
                    array( "fa fa-gbp" =>  "GBP" ),
                    array( "fa fa-ils" =>  "Shekel (ILS)" ),
                    array( "fa fa-inr" =>  "Indian Rupee (INR)" ),
                    array( "fa fa-jpy" =>  "Japanese Yen (JPY)" ),
                    array( "fa fa-krw" =>  "Korean Won (KRW)" ),
                    array( "fa fa-money" =>  "Money" ),
                    array( "fa fa-rub" =>  "Russian Ruble (RUB)" ),
                    array( "fa fa-try" =>  "Turkish Lira (TRY)" ),
                    array( "fa fa-usd" =>  "US Dollar" ),
                ),
                "Text Editor Icons" => array(
                    array( "fa fa-align-center" =>  "Align Center" ),
                    array( "fa fa-align-justify" =>  "Align Justify" ),
                    array( "fa fa-align-left" =>  "Align Left" ),
                    array( "fa fa-align-right" =>  "Align Right" ),
                    array( "fa fa-bold" =>  "Bold" ),
                    array( "fa fa-chain-broken" =>  "Chain Broken" ),
                    array( "fa fa-clipboard" =>  "Clipboard" ),
                    array( "fa fa-columns" =>  "Columns" ),
                    array( "fa fa-eraser" =>  "Eraser" ),
                    array( "fa fa-file" =>  "File" ),
                    array( "fa fa-file-o" =>  "File Outlined" ),
                    array( "fa fa-file-text" =>  "File Text" ),
                    array( "fa fa-file-text-o" =>  "File Text Outlined" ),
                    array( "fa fa-files-o" =>  "Files Outlined" ),
                    array( "fa fa-floppy-o" =>  "Floppy Outlined" ),
                    array( "fa fa-font" =>  "Font" ),
                    array( "fa fa-header" =>  "Header" ),
                    array( "fa fa-indent" =>  "Indent" ),
                    array( "fa fa-italic" =>  "Italic" ),
                    array( "fa fa-link" =>  "Link" ),
                    array( "fa fa-list" =>  "List" ),
                    array( "fa fa-list-alt" =>  "List alt" ),
                    array( "fa fa-list-ol" =>  "List ol" ),
                    array( "fa fa-list-ul" =>  "List ul" ),
                    array( "fa fa-outdent" =>  "Outdent" ),
                    array( "fa fa-paperclip" =>  "Paperclip" ),
                    array( "fa fa-paragraph" =>  "paragraph" ),
                    array( "fa fa-repeat" =>  "Repeat" ),
                    array( "fa fa-scissors" =>  "Scissors" ),
                    array( "fa fa-strikethrough" =>  "Strikethrough" ),
                    array( "fa fa-subscript" =>  "Subscript" ),
                    array( "fa fa-superscript" =>  "Superscript" ),
                    array( "fa fa-table" =>  "Table" ),
                    array( "fa fa-text-height" =>  "Text-height" ),
                    array( "fa fa-text-width" =>  "Text-width" ),
                    array( "fa fa-th" =>  "Th" ),
                    array( "fa fa-th-large" =>  "Th-large" ),
                    array( "fa fa-th-list" =>  "Th-list" ),
                    array( "fa fa-underline" =>  "Underline" ),
                    array( "fa fa-undo" =>  "Undo" ),
                ),
                "Directional Icons" => array(
                    array( "fa fa-angle-double-down" =>  "Angle Double Down" ),
                    array( "fa fa-angle-double-left" =>  "Angle Double Left" ),
                    array( "fa fa-angle-double-right" =>  "Angle Double Right" ),
                    array( "fa fa-angle-double-up" =>  "Angle Double Up" ),
                    array( "fa fa-angle-down" =>  "Angle Down" ),
                    array( "fa fa-angle-left" =>  "Angle Left" ),
                    array( "fa fa-angle-right" =>  "Angle Right" ),
                    array( "fa fa-angle-up" =>  "Angle Up" ),
                    array( "fa fa-arrow-circle-down" =>  "Arrow Circle Down" ),
                    array( "fa fa-arrow-circle-left" =>  "Arrow Circle Left" ),
                    array( "fa fa-arrow-circle-o-down" =>  "Arrow Circle Outlined Down" ),
                    array( "fa fa-arrow-circle-o-left" =>  "Arrow Circle Outlined Left" ),
                    array( "fa fa-arrow-circle-o-right" =>  "Arrow Circle Outlined Right" ),
                    array( "fa fa-arrow-circle-o-up" =>  "Arrow Circle Outlined Up" ),
                    array( "fa fa-arrow-circle-right" =>  "Arrow Circle Right" ),
                    array( "fa fa-arrow-circle-up" =>  "Arrow Circle Up" ),
                    array( "fa fa-arrow-down" =>  "Arrow Down" ),
                    array( "fa fa-arrow-left" =>  "Arrow Left" ),
                    array( "fa fa-arrow-right" =>  "Arrow Right" ),
                    array( "fa fa-arrow-up" =>  "Arrow Up" ),
                    array( "fa fa-arrows" =>  "Arrows" ),
                    array( "fa fa-arrows-alt" =>  "Arrows Alt" ),
                    array( "fa fa-arrows-h" =>  "Arrows Horizontal" ),
                    array( "fa fa-arrows-v" =>  "Arrows Vertical" ),
                    array( "fa fa-caret-down" =>  "Caret Down" ),
                    array( "fa fa-caret-left" =>  "Caret Left" ),
                    array( "fa fa-caret-right" =>  "Caret Right" ),
                    array( "fa fa-caret-square-o-down" =>  "Caret Square Outlined Down" ),
                    array( "fa fa-caret-square-o-left" =>  "Caret Square Outlined Left" ),
                    array( "fa fa-caret-square-o-right" =>  "Caret Square Outlined Right" ),
                    array( "fa fa-caret-square-o-up" =>  "Caret Square Outlined Up" ),
                    array( "fa fa-caret-up" =>  "Caret Up" ),
                    array( "fa fa-chevron-circle-down" =>  "Chevron Circle Down" ),
                    array( "fa fa-chevron-circle-left" =>  "Chevron Circle Left" ),
                    array( "fa fa-chevron-circle-right" =>  "Chevron Circle Right" ),
                    array( "fa fa-chevron-circle-up" =>  "Chevron Circle Up" ),
                    array( "fa fa-chevron-down" =>  "Chevron Down" ),
                    array( "fa fa-chevron-left" =>  "Chevron Left" ),
                    array( "fa fa-chevron-right" =>  "Chevron Right" ),
                    array( "fa fa-chevron-up" =>  "Chevron Up" ),
                    array( "fa fa-hand-o-down" =>  "Hand Outlined Down" ),
                    array( "fa fa-hand-o-left" =>  "Hand Outlined Left" ),
                    array( "fa fa-hand-o-right" =>  "Hand Outlined Right" ),
                    array( "fa fa-hand-o-up" =>  "Hand Outlined Up" ),
                    array( "fa fa-long-arrow-down" =>  "Long Arrow Down" ),
                    array( "fa fa-long-arrow-left" =>  "Long Arrow Left" ),
                    array( "fa fa-long-arrow-right" =>  "Long Arrow Right" ),
                    array( "fa fa-long-arrow-up" =>  "Long Arrow Up" ),
                ),
                "Video Player Icons" => array(
                    array( "fa fa-arrows-alt" =>  "Arrows Alt" ),
                    array( "fa fa-backward" =>  "Backward" ),
                    array( "fa fa-compress" =>  "Compress" ),
                    array( "fa fa-eject" =>  "Eject" ),
                    array( "fa fa-expand" =>  "Expand" ),
                    array( "fa fa-fast-backward" =>  "Fast Backward" ),
                    array( "fa fa-fast-forward" =>  "Fast Forward" ),
                    array( "fa fa-forward" =>  "Forward" ),
                    array( "fa fa-pause" =>  "Pause" ),
                    array( "fa fa-play" =>  "Play" ),
                    array( "fa fa-play-circle" =>  "Play Circle" ),
                    array( "fa fa-play-circle-o" =>  "Play Circle Outlined" ),
                    array( "fa fa-step-backward" =>  "Step Backward" ),
                    array( "fa fa-step-forward" =>  "Step Forward" ),
                    array( "fa fa-stop" =>  "Stop" ),
                    array( "fa fa-youtube-play" =>  "YouTube Play" ),
                    /*4.5*/
                    array( "fa fa-pause-circle" =>  "Pause Circle" ),
                    array( "fa fa-pause-circle-o" =>  "Pause Circle O" ),
                    array( "fa fa-stop-circle" =>  "Stop Circle" ),
                    array( "fa fa-stop-circle-o" =>  "Stop Circle O" ),
                ),
                "Brand Icons" => array(
                    array( "fa fa-adn" =>  "App.net" ),
                    array( "fa fa-android" =>  "Android" ),
                    array( "fa fa-angellist" =>  "AngelList" ),
                    array( "fa fa-apple" =>  "Apple" ),
                    array( "fa fa-behance" =>  "Behance" ),
                    array( "fa fa-behance-square" =>  "Behance Square" ),
                    array( "fa fa-bitbucket" =>  "Bitbucket" ),
                    array( "fa fa-bitbucket-square" =>  "Bitbucket Square" ),
                    array( "fa fa-btc" =>  "Bitcoin (BTC)" ),
                    array( "fa fa-cc-amex" =>  "American Express Credit Card" ),
                    array( "fa fa-cc-discover" =>  "Discover Credit Card" ),
                    array( "fa fa-cc-mastercard" =>  "MasterCard Credit Card" ),
                    array( "fa fa-cc-paypal" =>  "Paypal Credit Card" ),
                    array( "fa fa-cc-stripe" =>  "Stripe Credit Card" ),
                    array( "fa fa-cc-visa" =>  "Visa Credit Card" ),
                    array( "fa fa-codepen" =>  "Codepen" ),
                    array( "fa fa-css3" =>  "CSS 3 Logo" ),
                    array( "fa fa-delicious" =>  "Delicious Logo" ),
                    array( "fa fa-deviantart" =>  "deviantART" ),
                    array( "fa fa-digg" =>  "Digg Logo" ),
                    array( "fa fa-dribbble" =>  "Dribbble" ),
                    array( "fa fa-dropbox" =>  "Dropbox" ),
                    array( "fa fa-drupal" =>  "Drupal Logo" ),
                    array( "fa fa-empire" =>  "Galactic Empire" ),
                    array( "fa fa-facebook" =>  "Facebook" ),
                    array( "fa fa-facebook-square" =>  "Facebook Square" ),
                    array( "fa fa-flickr" =>  "Flickr" ),
                    array( "fa fa-foursquare" =>  "Foursquare" ),
                    array( "fa fa-git" =>  "Git" ),
                    array( "fa fa-git-square" =>  "Git Square" ),
                    array( "fa fa-github" =>  "GitHub" ),
                    array( "fa fa-github-alt" =>  "GitHub Alt" ),
                    array( "fa fa-github-square" =>  "GitHub Square" ),
                    array( "fa fa-gittip" =>  "Gittip" ),
                    array( "fa fa-google" =>  "Google Logo" ),
                    array( "fa fa-google-plus" =>  "Google Plus" ),
                    array( "fa fa-google-plus-square" =>  "Google Plus Square" ),
                    array( "fa fa-google-wallet" =>  "Goole Wallet" ),
                    array( "fa fa-hacker-news" =>  "Hacker News" ),
                    array( "fa fa-html5" =>  "HTML 5 Logo" ),
                    array( "fa fa-instagram" =>  "Instagram" ),
                    array( "fa fa-ioxhost" =>  "ioxhost" ),
                    array( "fa fa-joomla" =>  "Joomla Logo" ),
                    array( "fa fa-jsfiddle" =>  "jsFiddle" ),
                    array( "fa fa-lastfm" =>  "last.fm" ),
                    array( "fa fa-lastfm-square" =>  "last.fm Square" ),
                    array( "fa fa-linkedin" =>  "LinkedIn" ),
                    array( "fa fa-linkedin-square" =>  "LinkedIn Square" ),
                    array( "fa fa-linux" =>  "Linux" ),
                    array( "fa fa-maxcdn" =>  "MaxCDN" ),
                    array( "fa fa-meanpath" =>  "meanpath" ),
                    array( "fa fa-openid" =>  "OpenID" ),
                    array( "fa fa-pagelines" =>  "Pagelines" ),
                    array( "fa fa-paypal" =>  "Paypal" ),
                    array( "fa fa-pied-piper" =>  "Pied Piper Logo" ),
                    array( "fa fa-pied-piper-alt" =>  "Pied Piper Alternate Logo" ),
                    array( "fa fa-pinterest" =>  "Pinterest" ),
                    array( "fa fa-pinterest-square" =>  "Pinterest Square" ),
                    array( "fa fa-qq" =>  "QQ" ),
                    array( "fa fa-rebel" =>  "Rebel Alliance" ),
                    array( "fa fa-reddit" =>  "reddit Logo" ),
                    array( "fa fa-reddit-square" =>  "reddit Square" ),
                    array( "fa fa-renren" =>  "Renren" ),
                    array( "fa fa-share-alt" =>  "Share Alt" ),
                    array( "fa fa-share-alt-square" =>  "Share Alt Square" ),
                    array( "fa fa-skype" =>  "Skype" ),
                    array( "fa fa-slack" =>  "Slack Logo" ),
                    array( "fa fa-slideshare" =>  "Slideshare" ),
                    array( "fa fa-soundcloud" =>  "SoundCloud" ),
                    array( "fa fa-spotify" =>  "Spotify" ),
                    array( "fa fa-stack-exchange" =>  "Stack Exchange" ),
                    array( "fa fa-stack-overflow" =>  "Stack Overflow" ),
                    array( "fa fa-steam" =>  "Steam" ),
                    array( "fa fa-steam-square" =>  "Steam Square" ),
                    array( "fa fa-stumbleupon" =>  "StumbleUpon Logo" ),
                    array( "fa fa-stumbleupon-circle" =>  "StumbleUpon Circle" ),
                    array( "fa fa-tencent-weibo" =>  "Tencent Weibo" ),
                    array( "fa fa-trello" =>  "Trello" ),
                    array( "fa fa-tumblr" =>  "Tumblr" ),
                    array( "fa fa-tumblr-square" =>  "Tumblr Square" ),
                    array( "fa fa-twitch" =>  "Twitch" ),
                    array( "fa fa-twitter" =>  "Twitter" ),
                    array( "fa fa-twitter-square" =>  "Twitter Square" ),
                    array( "fa fa-vimeo-square" =>  "Vimeo Square" ),
                    array( "fa fa-vine" =>  "Vine" ),
                    array( "fa fa-vk" =>  "VK" ),
                    array( "fa fa-weibo" =>  "Weibo" ),
                    array( "fa fa-weixin" =>  "Weixin (WeChat)" ),
                    array( "fa fa-windows" =>  "Windows" ),
                    array( "fa fa-wordpress" =>  "Wordpress Logo" ),
                    array( "fa fa-xing" =>  "Xing" ),
                    array( "fa fa-xing-square" =>  "Xing Square" ),
                    array( "fa fa-yahoo" =>  "Yahoo Logo" ),
                    array( "fa fa-yelp" =>  "Yelp" ),
                    array( "fa fa-youtube" =>  "YouTube" ),
                    array( "fa fa-youtube-play" =>  "YouTube Play" ),
                    array( "fa fa-youtube-square" =>  "YouTube Square" ),
                    /*4.3*/
                    array( "fa fa-buysellads" => "Buysellads" ),
                    array( "fa fa-connectdevelop" => "Connectdevelop" ),
                    array( "fa fa-dashcube" => "Dashcube" ),
                    array( "fa fa-facebook-official" => "Facebook Official" ),
                    array( "fa fa-forumbee" => "Forumbee" ),
                    array( "fa fa-leanpub" => "Leanpub" ),
                    array( "fa fa-medium" => "Medium" ),
                    array( "fa fa-pinterest-p" => "Pinterest P" ),
                    array( "fa fa-sellsy" => "Sellsy" ),
                    array( "fa fa-shirtsinbulk" => "Shirtsinbulk" ),
                    array( "fa fa-simplybuilt" => "Simplybuilt" ),
                    array( "fa fa-skyatlas" => "Skyatlas" ),
                    /*4.4*/
                    array( "fa fa-500px" => "500px" ),
                    array( "fa fa-amazon" => "Amazon" ),
                    /*4.5*/
                    array( "fa fa-codiepie" => "Codiepie" ),
                    array( "fa fa-credit-card-alt" => "Credit Card Alt" ),
                    array( "fa fa-edge" => "Edge" ),
					array( "fa fa-fort-awesome" => "Fort Awesome" ),
					array( "fa fa-mixcloud" => "Mixcloud" ),
					array( "fa fa-modx" => "Modx" ),
					array( "fa fa-product-hunt" => "Product Hunt" ),
					array( "fa fa-reddit-alien" => "Reddit Alien" ),
					array( "fa fa-scribd" => "Scribd" ),
					array( "fa fa-usb" => "Usb" ),

                ),
                "Medical Icons" => array(
                    array( "fa fa-ambulance" =>  "Ambulance" ),
                    array( "fa fa-h-square" =>  "H Square" ),
                    array( "fa fa-hospital-o" =>  "Hospital Outlined" ),
                    array( "fa fa-medkit" =>  "Medkit" ),
                    array( "fa fa-plus-square" =>  "Plus Square" ),
                    array( "fa fa-stethoscope" =>  "Stethoscope" ),
                    array( "fa fa-user-md" =>  "User-md" ),
                    array( "fa fa-wheelchair" =>  "Wheelchair" ),
                ),
                /*4.3*/
                "Transportation Icons" => array(
                    array( "fa fa-subway" => "Subway" ),
                    array( "fa fa-train" => "Train" ),
                ),
                "Gender Icons" => array(
                    array( "fa fa-mars" => "Mars" ),
                    array( "fa fa-mars-double" => "Mars Double" ),
                    array( "fa fa-mars-stroke" => "Mars Stroke" ),
                    array( "fa fa-mars-stroke-h" => "Mars Stroke Horizontal" ),
                    array( "fa fa-mars-stroke-v" => "Mars Stroke Vertical" ),
                    array( "fa fa-mercury" => "Mercury" ),
                    array( "fa fa-neuter" => "Neuter" ),
                    array( "fa fa-transgender" => "Transgender" ),
                    array( "fa fa-transgender-alt" => "Transgender Alt" ),
                    array( "fa fa-venus" => "Venus" ),
                    array( "fa fa-venus-double" => "Venus Double" ),
                    array( "fa fa-venus-mars" => "Venus Mars" ),
                    array( "fa fa-viacoin" => "Viacoin" ),
                )
            );

            return $icons;
        }

        public function get_linecons_icons( $icons ){
        
            $icons = array(
		        array( "linecons-heart" => "Heart" ),
		        array( "linecons-cloud" => "Cloud" ),
		        array( "linecons-star" => "Star" ),
		        array( "linecons-tv" => "Tv" ),
		        array( "linecons-sound" => "Sound" ),
		        array( "linecons-video" => "Video" ),
		        array( "linecons-trash" => "Trash" ),
		        array( "linecons-user" => "User" ),
		        array( "linecons-key" => "Key" ),
		        array( "linecons-search" => "Search" ),
		        array( "linecons-settings" => "Settings" ),
		        array( "linecons-camera" => "Camera" ),
		        array( "linecons-tag" => "Tag" ),
		        array( "linecons-lock" => "Lock" ),
		        array( "linecons-bulb" => "Bulb" ),
		        array( "linecons-pen" => "Pen" ),
		        array( "linecons-diamond" => "Diamond" ),
		        array( "linecons-display" => "Display" ),
		        array( "linecons-location" => "Location" ),
		        array( "linecons-eye" => "Eye" ),
		        array( "linecons-bubble" => "Bubble" ),
		        array( "linecons-stack" => "Stack" ),
		        array( "linecons-cup" => "Cup" ),
		        array( "linecons-phone" => "Phone" ),
		        array( "linecons-news" => "News" ),
		        array( "linecons-mail" => "Mail" ),
		        array( "linecons-like" => "Like" ),
		        array( "linecons-photo" => "Photo" ),
		        array( "linecons-note" => "Note" ),
		        array( "linecons-clock" => "Clock" ),
		        array( "linecons-paperplane" => "Paperplane" ),
		        array( "linecons-params" => "Params" ),
		        array( "linecons-banknote" => "Banknote" ),
		        array( "linecons-data" => "Data" ),
		        array( "linecons-music" => "Music" ),
		        array( "linecons-megaphone" => "Megaphone" ),
		        array( "linecons-study" => "Study" ),
		        array( "linecons-lab" => "Lab" ),
		        array( "linecons-food" => "Food" ),
		        array( "linecons-t-shirt" => "T Shirt" ),
		        array( "linecons-fire" => "Fire" ),
		        array( "linecons-clip" => "Clip" ),
		        array( "linecons-shop" => "Shop" ),
		        array( "linecons-calendar" => "Calendar" ),
		        array( "linecons-wallet" => "Wallet" ),
		        array( "linecons-vynil" => "Vynil" ),
		        array( "linecons-truck" => "Truck" ),
		        array( "linecons-world" => "World" ),
	        );

            return $icons;
        }

        public function get_bigmug_line_icons( $icons ){
            $icons = array(
		        array( "bigmug-line-plus" => "Plus" ),
                array( "bigmug-line-plus-circle" => "Plus-circle" ),
                array( "bigmug-line-plus-square" => "Plus-square" ),
                array( "bigmug-line-airplane" => "airplane" ),
                array( "bigmug-line-alarm" => "Alarm" ),
                array( "bigmug-line-collapse1" => "Collapse1" ),
                array( "bigmug-line-attach1" => "Attach1" ),
                array( "bigmug-line-attach2" => "Attach2" ),
                array( "bigmug-line-volumn-off" => "Volumn-off" ),
                array( "bigmug-line-arrow-circle-left" => "Arrow-circle-left" ),
                array( "bigmug-line-arrow-square-left" => "Arrow-square-square" ),
                array( "bigmug-line-mappin" => "Map-pin" ),
                array( "bigmug-line-book" => "Book" ),
                array( "bigmug-line-bookmark" => "Bookmark" ),
                array( "bigmug-line-bottle" => "Bottle" ),
                array( "bigmug-line-th" => "Thumbnails" ),
                array( "bigmug-line-gamepad" => "Gamepad" ),
                array( "bigmug-line-tablet" => "Tablet" ),
                array( "bigmug-line-mobile" => "Mobile" ),
                array( "bigmug-line-align-center" => "Align-center" ),
                array( "bigmug-line-chat1" => "Chat1" ),
                array( "bigmug-line-chat2" => "Chat2" ),
                array( "bigmug-line-checkmark" => "Checkmark" ),
                array( "bigmug-line-checkmark-square" => "Checkmark-square" ),
                array( "bigmug-line-checkmark-circle" => "Checkmark-circle" ),
                array( "bigmug-line-certificate" => "Certificate" ),
                array( "bigmug-line-target" => "Target" ),
                array( "bigmug-line-pie-chart" => "Pie-chart" ),
                array( "bigmug-line-refresh" => "Refresh" ),
                array( "bigmug-line-clipboard" => "Clipboard" ),
                array( "bigmug-line-cross-circle" => "Cross-circle" ),
                array( "bigmug-line-cloud" => "Cloud" ),
                array( "bigmug-line-cloud-rain" => "Cloud-rain" ),
                array( "bigmug-line-glass" => "Glass" ),
                array( "bigmug-line-code" => "Code" ),
                array( "bigmug-line-collapse2" => "Collapse2" ),
                array( "bigmug-line-comment" => "Comment" ),
                array( "bigmug-line-compass" => "Compass" ),
                array( "bigmug-line-collapse-square" => "Collapse-square" ),
                array( "bigmug-line-copy" => "Copy" ),
                array( "bigmug-line-crescent" => "Crescent" ),
                array( "bigmug-line-cropping" => "Cropping" ),
                array( "bigmug-line-cross" => "Cross" ),
                array( "bigmug-line-cross-square" => "Cross-square" ),
                array( "bigmug-line-layer" => "Layer" ),
                array( "bigmug-line-arrow-v" => "Arrow-v" ),
                array( "bigmug-line-chavron-double-right" => "Arrow-double-right" ),
                array( "bigmug-line-arrow-h" => "Arrow-h" ),
                array( "bigmug-line-arrow-circle-down" => "Arrow-circle-down" ),
                array( "bigmug-line-arrow-square-down" => "Arrow-square-down" ),
                array( "bigmug-line-download1" => "Download1" ),
                array( "bigmug-line-chevron-square-down" => "Chevron-square-down" ),
                array( "bigmug-line-chevron-down" => "Chevron-down" ),
                array( "bigmug-line-download2" => "Download2" ),
                array( "bigmug-line-download3" => "Download3" ),
                array( "bigmug-line-download4" => "Download4" ),
                array( "bigmug-line-download5" => "Download5" ),
                array( "bigmug-line-arrow-circle-down" => "Arrow-circle-down" ),
                array( "bigmug-line-electrical" => "Electrical" ),
                array( "bigmug-line-electronic" => "Electronic" ),
                array( "bigmug-line-email1" => "Email1" ),
                array( "bigmug-line-email2" => "Email2" ),
                array( "bigmug-line-equalizar1" => "Equalizar1" ),
                array( "bigmug-line-equalizar2" => "Equalizar2" ),
                array( "bigmug-line-event" => "Event" ),
                array( "bigmug-line-expand-square" => "Expand-square" ),
                array( "bigmug-line-expand" => "Expand" ),
                array( "bigmug-line-forward" => "Forward" ),
                array( "bigmug-line-star" => "Star" ),
                array( "bigmug-line-file1" => "File1" ),
                array( "bigmug-line-file2" => "File2" ),
                array( "bigmug-line-film" => "Film" ),
                array( "bigmug-line-flag" => "Flag" ),
                array( "bigmug-line-foggy-moon" => "Foggy-moon" ),
                array( "bigmug-line-foggy-sun" => "Foggy-sun" ),
                array( "bigmug-line-folder" => "Folder" ),
                array( "bigmug-line-fork" => "Fork" ),
                array( "bigmug-line-th-large" => "Th-large" ),
                array( "bigmug-line-full" => "Full" ),
                array( "bigmug-line-gameboy" => "Gameboy" ),
                array( "bigmug-line-gear" => "Gear" ),
                array( "bigmug-line-giftbox" => "Giftbox" ),
                array( "bigmug-line-graphical" => "Graphical" ),
                array( "bigmug-line-headphones" => "Headphones" ),
                array( "bigmug-line-fire" => "Fire" ),
                array( "bigmug-line-images" => "Images" ),
                array( "bigmug-line-ink" => "Ink" ),
                array( "bigmug-line-tag1" => "Tag1" ),
                array( "bigmug-line-tag2" => "Tag2" ),
                array( "bigmug-line-tag3" => "Tag3" ),
                array( "bigmug-line-left-square" => "Left-square" ),
                array( "bigmug-line-chevron-left" => "Chevron-left" ),
                array( "bigmug-line-chevron-circle-left" => "Chevron-circle-left" ),
                array( "bigmug-line-chevron-square-left" => "Chevron-square-left" ),
                array( "bigmug-line-align-left" => "Align-left" ),
                array( "bigmug-line-undo" => "Undo" ),
                array( "bigmug-line-heart" => "Heart" ),
                array( "bigmug-line-link" => "Icon-googleplus" ),
                array( "bigmug-line-list1" => "List1" ),
                array( "bigmug-line-list2" => "List2" ),
                array( "bigmug-line-lock" => "Lock" ),
                array( "bigmug-line-login1" => "Login1" ),
                array( "bigmug-line-login2" => "Login2" ),
                array( "bigmug-line-map" => "Map" ),
                array( "bigmug-line-megaphone" => "Megaphone" ),
                array( "bigmug-line-menu-bar1" => "Menu-bar1" ),
                array( "bigmug-line-menu-bar2" => "Menu-bar2" ),
                array( "bigmug-line-menu-bar2" => "Menu-bar3" ),
                array( "bigmug-line-microphone1" => "Microphone1" ),
                array( "bigmug-line-microphone2" => "Microphone2" ),
                array( "bigmug-line-minus-circle" => "Minus-circle" ),
                array( "bigmug-line-minus-square" => "Minus-square" ),
                array( "bigmug-line-zoom-out" => "Zoom-out" ),
                array( "bigmug-line-minus" => "Minus" ),
                array( "bigmug-line-monitor" => "Monitor" ),
                array( "bigmug-line-music1" => "Music1" ),
                array( "bigmug-line-music2" => "Music2" ),
                array( "bigmug-line-music3" => "Music3" ),
                array( "bigmug-line-music4" => "Music4" ),
                array( "bigmug-line-music5" => "Music5" ),
                array( "bigmug-line-mute1" => "Mute1" ),
                array( "bigmug-line-mute2" => "Mute2" ),
                array( "bigmug-line-clock" => "Clock" ),
                array( "bigmug-line-edit" => "Edit" ),
                array( "bigmug-line-notebook" => "Notebook" ),
                array( "bigmug-line-notification1" => "Notification1" ),
                array( "bigmug-line-notification2" => "Notification2" ),
                array( "bigmug-line-email4" => "Email4" ),
                array( "bigmug-line-comment2" => "Comment2" ),
                array( "bigmug-line-brush" => "brush" ),
                array( "bigmug-line-paper-plane" => "Paper-plane" ),
                array( "bigmug-line-pause" => "Pause" ),
                array( "bigmug-line-pencil" => "Pencil" ),
                array( "bigmug-line-phone" => "Phone" ),
                array( "bigmug-line-camera" => "Camera" ),
                array( "bigmug-line-pin" => "Pin" ),
                array( "bigmug-line-planet" => "Planet" ),
                array( "bigmug-line-play" => "Play" ),
                array( "bigmug-line-portfolio" => "Portfolio" ),
                array( "bigmug-line-print" => "Print" ),
                array( "bigmug-line-radio" => "Radio" ),
                array( "bigmug-line-cloud-rain2" => "Cloud-rain2" ),
                array( "bigmug-line-comment3" => "Comment3" ),
                array( "bigmug-line-trash" => "Trash" ),
                array( "bigmug-line-rewind" => "Rewind" ),
                array( "bigmug-line-arrow-circle-righ" => "Circle-righ" ),
                array( "bigmug-line-map-signs" => "Map-signs" ),
                array( "bigmug-line-arrow-square-right" => "Arrow-square-right" ),
                array( "bigmug-line-right-square" => "Right-square" ),
                array( "bigmug-line-chevron-circle-right" => "Chevron-circle-right" ),
                array( "bigmug-line-redo" => "Redo" ),
                array( "bigmug-line-chevron-right" => "Chevron-right" ),
                array( "bigmug-line-chevron-square-right" => "Chevron-square-right" ),
                array( "bigmug-line-mouse" => "Mouse" ),
                array( "bigmug-line-hourglass" => "Hourglass" ),
                array( "bigmug-line-save" => "Save" ),
                array( "bigmug-line-search" => "Search" ),
                array( "bigmug-line-pin2" => "Pin2" ),
                array( "bigmug-line-share" => "share" ),
                array( "bigmug-line-shopping-bag" => "Shopping-bag" ),
                array( "bigmug-line-shopping-basket" => "Shopping-basket" ),
                array( "bigmug-line-shopping-cart1" => "Shopping-cart1" ),
                array( "bigmug-line-shopping-cart2" => "Shopping-cart2" ),
                array( "bigmug-line-shuffle" => "Shuffle" ),
                array( "bigmug-line-sort-up" => "Sort-up" ),
                array( "bigmug-line-sort-down" => "Sort-down" ),
                array( "bigmug-line-speaker" => "Speaker" ),
                array( "bigmug-line-speaker2" => "Speaker2" ),
                array( "bigmug-line-speaker3" => "Speaker3" ),
                array( "bigmug-line-volumn-up" => "Volumn-up" ),
                array( "bigmug-line-volumn-down" => "Volumn-down" ),
                array( "bigmug-line-speech" => "Speech" ),
                array( "bigmug-line-target-square" => "Target-square" ),
                array( "bigmug-line-square" => "Square" ),
                array( "bigmug-line-point" => "Point" ),
                array( "bigmug-line-store" => "Store" ),
                array( "bigmug-line-sun" => "Sun" ),
                array( "bigmug-line-sunrise" => "Sunrise" ),
                array( "bigmug-line-switch1" => "Switch1" ),
                array( "bigmug-line-switch2" => "Switch2" ),
                array( "bigmug-line-tag4" => "Tag4" ),
                array( "bigmug-line-television" => "Television" ),
                array( "bigmug-line-align-left" => "Align-left" ),
                array( "bigmug-line-text" => "Text" ),
                array( "bigmug-line-chart" => "Chart" ),
                array( "bigmug-line-timer" => "Timer" ),
                array( "bigmug-line-tool" => "Tool" ),
                array( "bigmug-line-triangle" => "Triangle" ),
                array( "bigmug-line-trophy" => "Trophy" ),
                array( "bigmug-line-refrash2" => "Refrash2" ),
                array( "bigmug-line-refrash3" => "Refrash3" ),
                array( "bigmug-line-tint" => "Tint" ),
                array( "bigmug-line-chevron-double-left" => "Chevron-double-left" ),
                array( "bigmug-line-clone" => "Clone" ),
                array( "bigmug-line-unlocked" => "Unlocked" ),
                array( "bigmug-line-chevron-circle-up" => "chevron-circle-u" ),
                array( "bigmug-line-spoon" => "Spoon" ),
                array( "bigmug-line-arrow-square-up" => "Arrow-square-up" ),
                array( "bigmug-line-upload" => "Upload" ),
                array( "bigmug-line-chevron-square-up" => "Chevron-square-up" ),
                array( "bigmug-line-home" => "Home" ),
                array( "bigmug-line-chevron-up" => "Chevron-up" ),
                array( "bigmug-line-up-square" => "Up-square" ),
                array( "bigmug-line-arrow-circle-up" => "Arrow-circle-up" ),
                array( "bigmug-line-up-square2" => "Up-square2" ),
                array( "bigmug-line-upload2" => "Upload2" ),
                array( "bigmug-line-upload3" => "Upload3" ),
                array( "bigmug-line-expand2" => "Expand2" ),
                array( "bigmug-line-user1" => "User1" ),
                array( "bigmug-line-user2" => "User2" ),
                array( "bigmug-line-video" => "Video" ),
                array( "bigmug-line-wallet" => "Wallet" ),
                array( "bigmug-line-weather" => "Weather" ),
                array( "bigmug-line-calendar1" => "Calendar1" ),
                array( "bigmug-line-calendar2" => "Calendar2" ),
                array( "bigmug-line-wind" => "Wind" ),
                array( "bigmug-line-window" => "Window" ),
                array( "bigmug-line-winds" => "Winds" ),
                array( "bigmug-line-wrench" => "Wrench" ),
                array( "bigmug-line-zoom-in" => "Zoom-in" )

	        );
            return $icons;
        }

        public function get_simple_line_icons( $icons ){
            $icons = array(
            	array( "sl-user-female" => "Female" ),
                array( "sl-user-follow" => "Follow" ),
                array( "sl-user-following" => "Following" ),
                array( "sl-user-unfollow" => "Unfollow" ),
                array( "sl-trophy" => "Trophy" ),
                array( "sl-screen-smartphone" => "Smartphone" ),
                array( "sl-screen-desktop" => "Desktop" ),
                array( "sl-plane" => "Plane" ),
                array( "sl-notebook" => "Notebook" ),
                array( "sl-moustache" => "Moustache" ),
                array( "sl-mouse" => "Mouse" ),
                array( "sl-magnet" => "Magnet" ),
                array( "sl-energy" => "Energy" ),
                array( "sl-emoticon-smile" => "Emoticon-smile" ),
                array( "sl-disc" => "Disc" ),
                array( "sl-cursor-move" => "Cursor-move" ),
                array( "sl-crop" => "Crop" ),
                array( "sl-credit-card" => "Credit-card" ),
                array( "sl-chemistry" => "Chemistry" ),
                array( "sl-user" => "User" ),
                array( "sl-speedometer" => "Speedometer" ),
                array( "sl-social-youtube" => "Youtube" ),
                array( "sl-social-twitter" => "Twitter" ),
                array( "sl-social-tumblr" => "Tumblr" ),
                array( "sl-social-facebook" => "Facebook" ),
                array( "sl-social-dropbox" => "Dropbox" ),
                array( "sl-social-dribbble" => "Dribbble" ),
                array( "sl-shield" => "Shield" ),
                array( "sl-screen-tablet" => "Tablet" ),
                array( "sl-magic-wand" => "Magic-wand" ),
                array( "sl-hourglass" => "Hourglass" ),
                array( "sl-graduation" => "Graduation" ),
                array( "sl-ghost" => "Ghost" ),
                array( "sl-game-controller" => "Game-controller" ),
                array( "sl-fire" => "Fire" ),
                array( "sl-eyeglasses" => "Eyeglasses" ),
                array( "sl-envelope-open" => "Envelope-open" ),
                array( "sl-envelope-letter" => "Envelope-letter" ),
                array( "sl-bell" => "Bell" ),
                array( "sl-badge" => "Badge" ),
                array( "sl-anchor" => "Anchor" ),
                array( "sl-wallet" => "Wallet" ),
                array( "sl-vector" => "Vector" ),
                array( "sl-speech" => "Speech" ),
                array( "sl-puzzle" => "Puzzle" ),
                array( "sl-printer" => "Printer" ),
                array( "sl-present" => "Present" ),
                array( "sl-playlist" => "Playlist" ),
                array( "sl-pin" => "Pin" ),
                array( "sl-picture" => "Picture" ),
                array( "sl-map" => "Map" ),
                array( "sl-layers" => "Layers" ),
                array( "sl-handbag" => "Handbag" ),
                array( "sl-globe-alt" => "Globe-alt" ),
                array( "sl-globe" => "Globe" ),
                array( "sl-frame" => "Frame" ),
                array( "sl-folder-alt" => "Folder-alt" ),
                array( "sl-film" => "Film" ),
                array( "sl-feed" => "Feed" ),
                array( "sl-earphones-alt" => "Earphones-alt" ),
                array( "sl-earphones" => "Earphones" ),
                array( "sl-drop" => "Drop" ),
                array( "sl-drawer" => "Drawer" ),
                array( "sl-docs" => "Docs" ),
                array( "sl-directions" => "Directions" ),
                array( "sl-direction" => "Direction" ),
                array( "sl-diamond" => "Diamond" ),
                array( "sl-cup" => "Cup" ),
                array( "sl-compass" => "Compress" ),
                array( "sl-call-out" => "Call-out" ),
                array( "sl-call-in" => "Call-in" ),
                array( "sl-call-end" => "Call-end" ),
                array( "sl-calculator" => "Calculator" ),
                array( "sl-bubbles" => "Bubbles" ),
                array( "sl-briefcase" => "Briefcase" ),
                array( "sl-book-open" => "Book-open" ),
                array( "sl-basket-loaded" => "Basket-loaded" ),
                array( "sl-basket" => "Basket" ),
                array( "sl-bag" => "Bag" ),
                array( "sl-action-undo" => "Action-undo" ),
                array( "sl-action-redo" => "Action-redo" ),
                array( "sl-wrench" => "Wrench" ),
                array( "sl-umbrella" => "Umbrella" ),
                array( "sl-trash" => "Trash" ),
                array( "sl-tag" => "Tag" ),
                array( "sl-support" => "Support" ),
                array( "sl-size-fullscreen" => "Size-fullscreen" ),
                array( "sl-size-actual" => "Size-actual" ),
                array( "sl-shuffle" => "Shuffle" ),
                array( "sl-share-alt" => "Share-alt" ),
                array( "sl-share" => "Share" ),
                array( "sl-rocket" => "Rocket" ),
                array( "sl-question" => "Question" ),
                array( "sl-pie-chart" => "Pie-chart" ),
                array( "sl-pencil" => "Pencil" ),
                array( "sl-note" => "Note" ),
                array( "sl-music-tone-alt" => "Music-tone-alt" ),
                array( "sl-music-tone" => "Music-tone" ),
                array( "sl-microphone" => "Microphone" ),
                array( "sl-loop" => "Loop" ),
                array( "sl-logout" => "Logout" ),
                array( "sl-login" => "Login" ),
                array( "sl-list" => "List" ),
                array( "sl-like" => "Like" ),
                array( "sl-home" => "Home" ),
                array( "sl-grid" => "Grid" ),
                array( "sl-graph" => "Graph" ),
                array( "sl-equalizer" => "Equalizer" ),
                array( "sl-dislike" => "Dislike" ),
                array( "sl-cursor" => "Cursor" ),
                array( "sl-control-start" => "Control-start" ),
                array( "sl-control-rewind" => "Control-rewind" ),
                array( "sl-control-play" => "Control-play" ),
                array( "sl-control-pause" => "Control-pause" ),
                array( "sl-control-forward" => "Control-forward" ),
                array( "sl-control-end" => "Control-end" ),
                array( "sl-calendar" => "Calendar" ),
                array( "sl-bulb" => "Bulb" ),
                array( "sl-bar-chart" => "Bar-chart" ),
                array( "sl-arrow-up" => "Arrow-up" ),
                array( "sl-arrow-right" => "Arrow-right" ),
                array( "sl-arrow-left" => "Arrow-left" ),
                array( "sl-arrow-down" => "Arrow-down" ),
                array( "sl-ban" => "Ban" ),
                array( "sl-bubble" => "Bubble" ),
                array( "sl-camcorder" => "Camcorder" ),
                array( "sl-camera" => "Camera" ),
                array( "sl-check" => "Check" ),
                array( "sl-clock" => "Clock" ),
                array( "sl-close" => "Close" ),
                array( "sl-cloud-download" => "Cloud-download" ),
                array( "sl-cloud-upload" => "Cloud-upload" ),
                array( "sl-doc" => "Doc" ),
                array( "sl-envelope" => "Envelope" ),
                array( "sl-eye" => "Eye" ),
                array( "sl-flag" => "Flag" ),
                array( "sl-folder" => "Folder" ),
                array( "sl-heart" => "Heart" ),
                array( "sl-info" => "Info" ),
                array( "sl-key" => "Key" ),
                array( "sl-link" => "Link" ),
                array( "sl-lock" => "Lock" ),
                array( "sl-lock-open" => "Lock-open" ),
                array( "sl-magnifier" => "Magnifier" ),
                array( "sl-magnifier-add" => "Magnifier-add" ),
                array( "sl-magnifier-remove" => "Magnifier-remove" ),
                array( "sl-paper-clip" => "Paper-clip" ),
                array( "sl-paper-plane" => "Paper-plane" ),
                array( "sl-plus" => "Plus" ),
                array( "sl-pointer" => "Pointer" ),
                array( "sl-power" => "Power" ),
                array( "sl-refresh" => "Refresh" ),
                array( "sl-reload" => "Reload" ),
                array( "sl-settings" => "Settings" ),
                array( "sl-star" => "Star" ),
                array( "sl-symbol-female" => "Symbol-female" ),
                array( "sl-symbol-male" => "Symbol-male" ),
                array( "sl-target" => "Target" ),
                array( "sl-volume-1" => "Volume-1" ),
                array( "sl-volume-2" => "Volume-2" ),
                array( "sl-volume-off" => "Volume-off" ),
                array( "sl-users" => "Users" ),
	        );
            return $icons;
        }

        public function get_blog_masonry_layout( $layout = '' ){
            
            $masonry_layout = array();

          	switch( $layout ){
		        case 'w-masonry':
		        $masonry_layout = array('w-item w-w2 w-h2', 'w-item', 'w-item w-h2', 'w-item w-h2', 'w-item', 'w-item w-w2', 'w-item w-item-h', 'w-item', 'w-item w-w2 w-h2', 'w-item w-h2', 'w-item w-w2', 'w-item w-h2', 'w-item', 'w-item w-item-h', 'w-item', 'w-item w-h2', 'w-item w-w2 w-h2', 'w-item w-h2', 'w-item w-w2', 'w-item', 'w-item w-item-h');
		        break;
		        default:
		        $masonry_layout = array('w-item', 'w-item w-h2', 'w-item', 'w-item w-h2', 'w-item w-h2', 'w-item w-h2', 'w-item', 'w-item');
		        break;
		    }

		    return $masonry_layout;
		}

        public function get_portfolio_masonry_layout( $layout = '' ){
             
            $masonry_layout = array();
		      
            switch( $layout ){
		        case 'masonry':
		        $masonry_layout = array('w-item w-h2', 'w-item w-w2 w-h2', 'w-item', 'w-item', 'w-item', 'w-item', 'w-item w-w2 w-h2', 'w-item w-w2', 'w-item w-w2 w-h2', 'w-item', 'w-item w-h2', 'w-item');
		        break;
		        default:
		        $masonry_layout = array('w-item', 'w-item w-h2');
		        break;
		    }

		    return $masonry_layout;
		}

		public function get_gallery_masonry_layout( $layout = '' ){
			
            $masonry_layout = array();
	        
            switch( $layout ){
	            case '1':
	            $masonry_layout = array('w-item', 'w-item w-h2', 'w-item', 'w-item w-h2', 'w-item w-h2', 'w-item w-h2', 'w-item', 'w-item');
	            break;
	            case '2':
	            $masonry_layout = array('w-item w-h2', 'w-item', 'w-item w-h2', 'w-item', 'w-item', 'w-item w-h2', 'w-item w-h2', 'w-item w-h2', 'w-item w-h2', 'w-item', 'w-item');
	            break;
	            default:
	            $masonry_layout = $this->get_portfolio_masonry_layout( 'masonry' );
	            break;
	        }

	        return $masonry_layout;
		}

	}

	new Overlap_Shortcode();

}